runtime: custom
env: flex

manual_scaling:
  instances: 1

resources:
  cpu: 0.1
  memory_gb: 0.9
  disk_size_gb: 10

network:
  forwarded_ports:
    - 65080
  instance_tag: websocket

env_variables:
  DB_URI: "/db/prod.db"
  ROOM_URL: "https://qrchatroom.df.r.appspot.com/room/"
  GOOGLE_PROJECT_ID: "qrchatroom"
  GOOGLE_BUCKET: "qrchatroom.appspot.com"
  WEBSOCKET_TYPE: "wss"

